### ISSUE TITLE
Create apps-production

### ISSUE THREAD

**Issue by nionis** [Rpc-h/applications#17]
### Description

As per what we discussed in the meeting (@nionis @ausias-armesto), the current plan has changed to:

- Create 18 more HOPR nodes on GKE. As per @ausias-armesto , this has to be done manually.
- Create 20 new RPCH exit nodes on GKE. As of now, there is no automated/easy way of doing this as every exit node requires it's own, unique variables like `HOPRD_API_TOKEN`, `HOPRD_PASSWORD`, and `RPCH_PRIVATE_KEY`. It means that we have to create the RPCH exit node applications and sealed-secrets by hand.
- Register the RPCH exit nodes using the script available. Similar to the previous point regarding RPCH exit nodes, this is a manual job as of now but should be automated using RPCH operator later in the future.

### Relevant issues

- [ ] Create 18 more HOPR nodes on GKE
- [ ] Create 20 new RPCH exit nodes on GKE
- [ ] Register the RPCH exit nodes using the script available

### Definition of DONE

TBD

**Comment by nionis** [comment]
@sitilge can you update the new plan in the issue description?

**Comment by ausias-armesto** [comment]
The `ClusterHoprd` is partially implemented, it allows you to create those bunch of nodes but later is not implemented the behaviour of modification. So I would encourage, as for now, to keep using `Hoprd`.

**Comment by nionis** [comment]
hey guys, can someone update the definition of done?

**Comment by nionis** [comment]
@tolbrino
